'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { CssBaseline } from "@mui/material";
import { LanguageProvider } from "./contexts/LanguageContext";
import { SnackbarProvider } from "./contexts/SnackbarProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  palette: {
    // background:{
    //   default: "#c8c2ae"
    //   paper: "#1F0812"
    // },
    // primary: {
    //   main: "#746D75", // default blue
    // },
    // secondary: {
    //   main: "#121619", // optional
    // },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{  }}
      >
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <LanguageProvider>
            <SnackbarProvider>
              {children}
            </SnackbarProvider>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
