"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Button, CircularProgress, CssBaseline } from "@mui/material";
import { LanguageProvider, useLanguage } from "./contexts/LanguageContext";
import {
  Severity,
  SnackbarProvider,
  useSnackbar,
} from "./contexts/SnackbarProvider";
import { usePathname, useRouter } from "next/navigation";
import { ReactNode, useEffect } from "react";
import { signOut } from "next-auth/react";
import Navbar from "./components/navbar";
import api, { getUserByToken, UserHeaderType } from "./axios";
import { useTranslation } from "react-i18next";
import { AuthProvider } from "./contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  palette: {
    background: {
      default: "#fff0db",
      //   paper: "#1F0812"
    },
    // primary: {
    //   main: "#746D75", // default blue
    // },
    // secondary: {
    //   main: "#121619", // optional
    // },
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{}}
      >
        <ThemeProvider theme={theme}>
          <AuthProvider>
            {/* <AuthGuard> */}
            <CssBaseline />
            <LanguageProvider>
              <SnackbarProvider>
                <Navbar />
                {children}
              </SnackbarProvider>
            </LanguageProvider>
            {/* </AuthGuard> */}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

function AuthGuard({ children }: { children: ReactNode }) {
  const router = useRouter();
  const pathname = usePathname();
  const { setLanguage } = useLanguage();
  const { showMessage } = useSnackbar();
  const { t } = useTranslation("common");

  useEffect(() => {
    async function getAuth() {
      return await getUserByToken();
    }
    const auth = getAuth();
    if (!auth && !pathname.startsWith("/auth")) router.push("/auth/login");

    async function fetchUserSettings() {
      try {
        const _auth = await getUserByToken();
        const settings = await api.get<{
          language: {
            id: string;
            code: string;
            name: string;
          };
        }>(`/user-settings/${_auth!.user.id}`);
        setLanguage(settings.data.language.code.split("-")[0]);
      } catch (err) {
        showMessage(t("fetch_settings_fail"), Severity.error);
      }
    }

    fetchUserSettings();
  }, [router, pathname]);

  return <></>;
}
